name: Build
on: [push, pull_request]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - uses: cachix/install-nix-action@v8
    - uses: cachix/cachix-action@v6
      with:
        name: mpickering
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: cachix use iohk
    - run: nix-build -A eventlog2html --arg ci true --argstr haskellCompiler ghc865
    - run: nix-build -A eventlog2html --arg ci true --argstr haskellCompiler ghc881


